services:
    Bluesquare\BillingBundle\Service\:
        resource: "../../Service/*"
        public: true
        arguments:
            $container: "@service_container",
            $manager: "@doctrine.orm.entity_manager"
            $env: '%kernel.environment%'

    Bluesquare\BillingBundle\Controller\:
        resource: "../../Controller/*"
        tags: ['controller.service_arguments']
        arguments:
            $container: "@service_container"
            $logger: "@logger"

