services:
    Bluesquare\BillingBundle\Service\:
        resource: "../../Service/*"
        public: true
        arguments: ["@service_container","@doctrine.orm.entity_manager",'%kernel.environment%']

    Bluesquare\BillingBundle\Controller\:
        resource: "../../Controller/*"
        tags: ['controller.service_arguments']
        arguments:
            $container: "@service_container"
            $logger: "@logger"

