services:
    Bluesquare\BillingBundle\Service\:
        resource: "../../Service/*"
        public: true
        arguments:
            $container: "@service_container"

    Bluesquare\BillingBundle\Controller\:
        resource: "../../Controller/*"
        tags: ['controller.service_arguments']
        arguments:
            $container: "@service_container"
            $logger: "@logger"

