services:
    Bluesquare\BillingBundle\Service\:
        resource: "../../Service/*"
        arguments:
            $container: "@service_container"

    Bluesquare\Controller\:
        resource: "../../Controller/*"
        arguments:
            $container: "@service_container"
            $logger: "@logger"

